spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}}:${DB_PORT}}/${DB_NAME}}
    username: ${DB_USERNAME}}
    password: ${DB_PASSWORD}}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update